version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Lambda functions..."
      - cd lambdas
      - npm run build
  

  

