version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Setting up AWS CLI..."
      - aws --version
  build:
    commands:
      - echo "Packaging Lambda functions..."
      - aws cloudformation package --template-file template.yaml --s3-bucket imgorig--output-template-file packaged.yaml
  post_build:
    commands:
      - echo "Deploying Lambda functions to AWS..."
      - aws cloudformation deploy --template-file packaged.yaml --stack-name t1--capabilities CAPABILITY_IAM

artifacts:
  files:
    - packaged.yaml

