AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lambda functions'

Resources:
  Func1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: './lambdas/LF1.zip'
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::540180955589:role/lambdafunciton1'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: imgorig
            Events:
              - 's3:ObjectCreated:Put'

  Func2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: './lambdas/LF2.zip'
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::540180955589:role/lambdafunciton2'
      Events:
        PhotoApi:
          Type: Api
          Properties:
            Path: /search
            Method: GET
