AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create an S3 bucket for hosting a frontend application

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: photosearch-frontend-s3
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebsiteURL:
    Description: URL for the frontend application hosted on S3
    Value: !GetAtt FrontendBucket.WebsiteURL

