AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: P1

Resources:
  frontendphotosearchs3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: frontend-photosearch-s3

  photosearchbuckets3:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: photosearch-bucket-s3

  LF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LF1
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::540180955589:role/service-role/index-photos-role-ycr1189e'

      Layers:
        - 'arn:aws:lambda:us-west-2:113088814899:layer:Klayers-python37-boto3:51'
        - >-
          arn:aws:lambda:us-west-2:113088814899:layer:Klayers-python37-requests:15
        - 'arn:aws:lambda:us-west-2:540180955589:layer:dependencies:1'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: photosearchbuckets3
            Events:
              - 's3:ObjectCreated:Put'

  LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./LF2
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::540180955589:role/service-role/search-photos-role-xlammunu'
      Layers:
        - >-
          arn:aws:lambda:us-west-2:113088814899:layer:Klayers-python37-requests:15
        - 'arn:aws:lambda:us-west-2:113088814899:layer:Klayers-python37-boto3:51'
        - 'arn:aws:lambda:us-west-2:540180955589:layer:dependencies:1'

      Events:
        PhotoApi:
          Type: Api
          Properties:
            Path: /search
            Method: GET


  PermissionForS3ToLF1:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LF1
      Principal: s3.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: "arn:aws:s3:::photosearch-bucket-s3"

  OpenSearchServiceDomain:
    Type: AWS::OpenSearchService::Domain

